# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 493)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.welcome_tab = QtWidgets.QWidget()
        self.welcome_tab.setObjectName("welcome_tab")
        self.textBrowser = QtWidgets.QTextBrowser(self.welcome_tab)
        self.textBrowser.setGeometry(QtCore.QRect(-10, -10, 811, 451))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.welcome_tab, "")
        self.config_tab = QtWidgets.QWidget()
        self.config_tab.setObjectName("config_tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.config_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 761, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.destinationHostLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.destinationHostLabel.setObjectName("destinationHostLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.destinationHostLabel)
        self.destinationHostLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.destinationHostLineEdit.setObjectName("destinationHostLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.destinationHostLineEdit)
        self.redisHostLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.redisHostLabel.setObjectName("redisHostLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.redisHostLabel)
        self.redisHostLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.redisHostLineEdit.setObjectName("redisHostLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.redisHostLineEdit)
        self.redisServicePortLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.redisServicePortLabel.setObjectName("redisServicePortLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.redisServicePortLabel)
        self.redisServicePortLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.redisServicePortLineEdit.setObjectName("redisServicePortLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.redisServicePortLineEdit)
        self.redisPasswordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.redisPasswordLabel.setObjectName("redisPasswordLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.redisPasswordLabel)
        self.redisPasswordLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.redisPasswordLineEdit.setObjectName("redisPasswordLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.redisPasswordLineEdit)
        self.tImeoutLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.tImeoutLabel.setObjectName("tImeoutLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.tImeoutLabel)
        self.tImeoutLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.tImeoutLineEdit.setObjectName("tImeoutLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tImeoutLineEdit)
        self.pushButton = QtWidgets.QPushButton(self.config_tab)
        self.pushButton.setGeometry(QtCore.QRect(689, 190, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.save_notice = QtWidgets.QTextBrowser(self.config_tab)
        self.save_notice.setGeometry(QtCore.QRect(10, 190, 681, 31))
        self.save_notice.setObjectName("save_notice")
        self.tabWidget.addTab(self.config_tab, "")
        self.scan_host_tab = QtWidgets.QWidget()
        self.scan_host_tab.setObjectName("scan_host_tab")
        self.generate_btn = QtWidgets.QPushButton(self.scan_host_tab)
        self.generate_btn.setGeometry(QtCore.QRect(20, 20, 151, 26))
        self.generate_btn.setObjectName("generate_btn")
        self.generate_note = QtWidgets.QTextBrowser(self.scan_host_tab)
        self.generate_note.setGeometry(QtCore.QRect(170, 70, 281, 41))
        self.generate_note.setObjectName("generate_note")
        self.stop_btn_1 = QtWidgets.QPushButton(self.scan_host_tab)
        self.stop_btn_1.setGeometry(QtCore.QRect(200, 20, 80, 26))
        self.stop_btn_1.setObjectName("stop_btn_1")
        self.start_btn = QtWidgets.QPushButton(self.scan_host_tab)
        self.start_btn.setGeometry(QtCore.QRect(20, 230, 151, 26))
        self.start_btn.setObjectName("start_btn")
        self.stop_btn_2 = QtWidgets.QPushButton(self.scan_host_tab)
        self.stop_btn_2.setGeometry(QtCore.QRect(200, 230, 80, 26))
        self.stop_btn_2.setObjectName("stop_btn_2")
        self.scan_note = QtWidgets.QTextBrowser(self.scan_host_tab)
        self.scan_note.setGeometry(QtCore.QRect(170, 270, 281, 41))
        self.scan_note.setObjectName("scan_note")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.scan_host_tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 70, 151, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.scan_host_tab)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 270, 151, 41))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label = QtWidgets.QLabel(self.scan_host_tab)
        self.label.setGeometry(QtCore.QRect(570, 20, 121, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.scan_host_tab)
        self.label_2.setGeometry(QtCore.QRect(700, 20, 81, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scan_host_tab)
        self.label_3.setGeometry(QtCore.QRect(640, 60, 51, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.scan_host_tab)
        self.label_4.setGeometry(QtCore.QRect(700, 60, 81, 18))
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.scan_host_tab)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 20, 61, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.scan_host_tab, "")
        self.get_certs_tab = QtWidgets.QWidget()
        self.get_certs_tab.setObjectName("get_certs_tab")
        self.load_certs_btn = QtWidgets.QPushButton(self.get_certs_tab)
        self.load_certs_btn.setGeometry(QtCore.QRect(140, 20, 80, 26))
        self.load_certs_btn.setObjectName("load_certs_btn")
        self.HostName = QtWidgets.QListView(self.get_certs_tab)
        self.HostName.setGeometry(QtCore.QRect(10, 60, 351, 371))
        self.HostName.setObjectName("HostName")
        self.get_certs_btn = QtWidgets.QPushButton(self.get_certs_tab)
        self.get_certs_btn.setGeometry(QtCore.QRect(540, 20, 80, 26))
        self.get_certs_btn.setObjectName("get_certs_btn")
        self.get_certs_finish = QtWidgets.QTextBrowser(self.get_certs_tab)
        self.get_certs_finish.setGeometry(QtCore.QRect(400, 60, 361, 371))
        self.get_certs_finish.setObjectName("get_certs_finish")
        self.tabWidget.addTab(self.get_certs_tab, "")
        self.check_certs_tab = QtWidgets.QWidget()
        self.check_certs_tab.setObjectName("check_certs_tab")
        self.pushButton_8 = QtWidgets.QPushButton(self.check_certs_tab)
        self.pushButton_8.setGeometry(QtCore.QRect(140, 20, 80, 26))
        self.pushButton_8.setObjectName("pushButton_8")
        self.CertsList = QtWidgets.QListView(self.check_certs_tab)
        self.CertsList.setGeometry(QtCore.QRect(10, 60, 351, 371))
        self.CertsList.setObjectName("CertsList")
        self.check_cert_btn = QtWidgets.QPushButton(self.check_certs_tab)
        self.check_cert_btn.setGeometry(QtCore.QRect(540, 20, 80, 26))
        self.check_cert_btn.setObjectName("check_cert_btn")
        self.check_notes = QtWidgets.QTextBrowser(self.check_certs_tab)
        self.check_notes.setGeometry(QtCore.QRect(400, 100, 361, 331))
        self.check_notes.setObjectName("check_notes")
        self.check_pgr = QtWidgets.QProgressBar(self.check_certs_tab)
        self.check_pgr.setGeometry(QtCore.QRect(400, 60, 361, 23))
        self.check_pgr.setProperty("value", 24)
        self.check_pgr.setObjectName("check_pgr")
        self.tabWidget.addTab(self.check_certs_tab, "")
        self.check_results_tab = QtWidgets.QWidget()
        self.check_results_tab.setObjectName("check_results_tab")
        self.export_btn = QtWidgets.QPushButton(self.check_results_tab)
        self.export_btn.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.export_btn.setObjectName("export_btn")
        self.export_notice = QtWidgets.QTextBrowser(self.check_results_tab)
        self.export_notice.setGeometry(QtCore.QRect(10, 70, 781, 361))
        self.export_notice.setObjectName("export_notice")
        self.tabWidget.addTab(self.check_results_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConfig = QtWidgets.QAction(MainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(MainWindow.save_config)
        self.load_certs_btn.clicked.connect(MainWindow.load_websites)
        self.pushButton_8.clicked.connect(MainWindow.load_certs)
        self.get_certs_btn.clicked.connect(MainWindow.get_certs)
        self.check_cert_btn.clicked.connect(MainWindow.check_certs)
        self.export_btn.clicked.connect(MainWindow.export_xls)
        self.generate_btn.clicked.connect(MainWindow.start_generate_list)
        self.start_btn.clicked.connect(MainWindow.start_scan)
        self.stop_btn_1.clicked.connect(MainWindow.stop_generate_list)
        self.stop_btn_2.clicked.connect(MainWindow.stop_scan)
        self.pushButton_2.clicked.connect(MainWindow.update_redis_status)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "X.509 Digital Certificate Compliance Checking System v1.0"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">X.509 Digital Certificate Compliance Checking System </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">(v1.0)</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.welcome_tab), _translate("MainWindow", "Welcome"))
        self.destinationHostLabel.setText(_translate("MainWindow", "Destination Host"))
        self.redisHostLabel.setText(_translate("MainWindow", "Redis Host"))
        self.redisServicePortLabel.setText(_translate("MainWindow", "Redis Service port"))
        self.redisPasswordLabel.setText(_translate("MainWindow", "Redis Password"))
        self.tImeoutLabel.setText(_translate("MainWindow", "TImeout"))
        self.pushButton.setText(_translate("MainWindow", "Save"))
        self.save_notice.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_tab), _translate("MainWindow", "Config"))
        self.generate_btn.setText(_translate("MainWindow", "Generate Scan List"))
        self.generate_note.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">0</span></p></body></html>"))
        self.stop_btn_1.setText(_translate("MainWindow", "Stop"))
        self.start_btn.setText(_translate("MainWindow", "Start Scan"))
        self.stop_btn_2.setText(_translate("MainWindow", "Stop"))
        self.scan_note.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">0</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">待扫描IP数量：</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">已扫描IP数量：</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Redis数据库连接状态"))
        self.label_2.setText(_translate("MainWindow", "Disconnected"))
        self.label_3.setText(_translate("MainWindow", "工作状态"))
        self.label_4.setText(_translate("MainWindow", "Stoped"))
        self.pushButton_2.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scan_host_tab), _translate("MainWindow", "Scan Host"))
        self.load_certs_btn.setText(_translate("MainWindow", "Load"))
        self.get_certs_btn.setText(_translate("MainWindow", "Get Certs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.get_certs_tab), _translate("MainWindow", "Get Certs"))
        self.pushButton_8.setText(_translate("MainWindow", "Load"))
        self.check_cert_btn.setText(_translate("MainWindow", "Check Certs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.check_certs_tab), _translate("MainWindow", "Check Certs"))
        self.export_btn.setText(_translate("MainWindow", "Export Excel File"))
        self.export_notice.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.check_results_tab), _translate("MainWindow", "Check Results"))
        self.actionConfig.setText(_translate("MainWindow", "Config"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
